### PR TITLE
allow php8

### PR DESCRIPTION
**Pull request by marvinosswald**
i'm going to create a series of pr all over related packages to https://github.com/contentful/contentful-laravel

prs:

- https://github.com/contentful/contentful-core.php/pull/44
- https://github.com/contentful/contentful-laravel/pull/40
- https://github.com/contentful/rich-text.php/pull/56
- https://github.com/contentful/contentful.php/pull/296

### CODE REVIEW

**Comment by theissn** [comment]
any idea when anyone might have a peek at these?

**Comment by brettmc** [comment]
Hello, I tried installing your branch(es) via composer - however:
```
Problem 1
    - Root composer.json requires contentful/core dev-php8 as 6.99 -> satisfiable by contentful/core[dev-php8].
    - contentful/core dev-php8 requires php ^7.2|8.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires contentful/contentful dev-php8 as 3.99 -> satisfiable by contentful/contentful[dev-php8].
    - contentful/contentful dev-php8 requires php ^7.2|8.0 -> your php version (8.0.2) does not satisfy that requirement.
```
I think that the version constraint needs to be relaxed. It looks like `^7.2|8.0` will only install exactly on php 8.0.0, but not dot releases. I think `^7.2|^8.0` is required (or maybe even `^7.2|^8` so as not to allow 8.1 before it's known whether the SDK will work in a future version.

I'd be happy to pitch in and help get contentful's PHP SDK running on php8 - I think a few more issues will come up (for example setting up CI builds for php8 in the same way as has been done for php7.x will use xdebug v3, which cannot generate code coverage for the current version of phpunit-code-coverage, which I believe requires an update to phpunit, which is then not compatible with php7.2, and faces a couple of (minor) deprecations. Although php 7.2 is out of support, the maintainers may wish to continue to support it if some of their customer base is still on this old version).

**Comment by marvinosswald** [comment]
@brettmc that is definitely a bad on my side yes it should be `^7.2|^8.0`.

**Comment by Sebb767** [comment]
Hi @marvinosswald ,

I just released v6.1.0, which now supports php8 :)

As with the other PRs, I did the required changes myself in order to check the code, update the CI etc., but I appreciate your PRs!

**Pull request closed without merging**
