### PR TITLE
added getFields to retrieve fields

### PR DESCRIPTION
**Pull request by etwillbefine**
Added the `getFields` method on DynamicEntry to retrieve fields. This gives us the opportunity to check whether properties exist or not. The problem ist, that currently I don't see any chance to keep track on non existent properties (no "magic method" should be called in that case). 

Would be great to merge that.
Thanks.

Otherwise we could add a method to check for existing properties (eg: `propertyExist($name)`)
/cc @realityking

### CODE REVIEW

**Comment by etwillbefine** [comment]
Any chance to get a reply on this?

**Comment by etwillbefine** [comment]
@realityking ?

**Comment by Haehnchen** [comment]
+1

**Comment by lukewduncan** [comment]
+1

**Comment by realityking** [comment]
@etwillbefine @Haehnchen @lukewduncan I got an alternate proposal in in pull request #49. Could you check if that'd address your requirements? Thank you.

**Comment by etwillbefine** [comment]
Hm imo this does not solve the issue. One of the advantages of using this sdk is the provided mapping/linking (basically the [ResourceBuilder](https://github.com/contentful/contentful.php/blob/master/src/Delivery/ResourceBuilder.php)). 
Why the user should be forced to retrieve data in raw format just to check whether a field exists or not?

**Comment by realityking** [comment]
Thanks for the feedback. I think I operated under an incorrect assumption. Maybe you can clarify a bit why you're checking for properties?

Do you know the _field_ exists and you want to check if it has content? Or do you want to check if the field/property is even part of the content model?

**Comment by etwillbefine** [comment]
This PR is about to check whether the field/property is part of the content model. This issue is quite old and I cannot remember the exact use case anymore. But imagine you want to extend the DynamicEntry and a content-model may contains an additional field/id/another model/whatever and you don't want to force the author to add this field to the content-MODEL (as you only want to do some stuff if its present). (these use cases assumes that you don't control the contentful cms side completely or you want to treat some objects on an abstract view)

Example:
```php
class TrackableEntry extends DynamicEntry {
    // only one or even none of these property are required in the content-model

    public function hasTrackingInformation() {
       return (woha how can I do this?)
    }
    public function hasTrackingEventName() {
       return (woha how can I do this?)
   }
}

public class EventListener {
     public function onEvent(DynamicEntry $e) {
         log.info($e->getId(), $e->getAuthorId()); 
        // uuh, triggers php error if entry doesn't have an author id attached
        // ok lets try to log it in a different way when the author-id is attached
        // woha how can I do this? 
    }
}

public class Mapper {
     public function map(DynamicEntry $e) {
         $entry = new MyCustomObject();
         $entry->id = $e->getId(); // great!
         $entry->name = $e->getName(); // fine as the name is required

         $entry->images = $e->getImages(); // oups, it may only contains `image` or `images`
         // lets check if images or image was provided, woha how can I do this?
    }
}

....
```

So as a conclusion to try to clarify the use case behind that: If the service grows and you want to unify some code for all content-types or if you want to treat a "wrong/misconfigured content-model" in a proper way you must be somehow able to look behind the scenes. 

If you don't want to make all fields accessible using this `getFields` method, as I said another way could be to add a method to check whether a property exists or not. The DynamicEntry is not very easy to extend, but imo it would be better to stay open for extension. From the point of view it is very similar to this issue https://github.com/contentful/contentful.php/issues/7

I know that `sys` is protected in the DynamicEntry, but that seems similar to retrieving data in raw format. I'd not appreciate it.

*As I did nothing related to contentful the last 3 months maybe I missed something?!*

**Pull request closed without merging**
