### PR TITLE
Ensure PSR-2 coding style is respected.

### PR DESCRIPTION
**Pull request by lucasmichot**
Ensure PSR-2 coding style is respected.

Fixing the coding-style can be achived by running: `./vendor/bin/php-cs-fixer fix`

### CODE REVIEW

**Comment by realityking** [comment]
Hi Lucas!

Love the fixes but I'd like to avoid adding more dependencies to `require-dev` (they tend to conflict after a while). Could you make use of the `.phar` version instead. Thanks :)

**Comment by lucasmichot** [comment]
Sure, just removed the dependency in https://github.com/contentful/contentful.php/pull/25/commits/b16467baf6be401dfc2155e021afb8cf23c2e0ca

**Comment by realityking** [comment]
Gee you're quick. You'll also have to remove `.php_cs` and revert `.gitignore` since those changes are now redundant.

Thanks again :)

**Comment by lucasmichot** [comment]
Well in fact this is the fixing definition file that can be used using the phar version of PHP-CS
This allows to avoid typing the fixing arguments in the CLI

**Comment by realityking** [comment]
I didn't know that. In this case 👍

**Pull request merged**
