### PR TITLE
Run static analysis using Phpstan

### PR DESCRIPTION
**Pull request by Jalle19**
Figured it can't hurt. Going above level 2 requires some major type-hint changes so I didn't bother. Level 1 catches the biggest issues anyway so it should be fine.

### CODE REVIEW

**Comment by dborsatto** [comment]
I'm already running PHPStan locally (without using that as a dependency), and unfortunately because of the generic nature of certain parts of the SDK, going above level 2 causes major type inference problems. PHPStan does its best, but they're definitely false positives (that's where actual tests come into play)...

I'm waiting for the build status to see if it works 😁 if it does, then it's definitely a 👍

**Comment by Jalle19** [comment]
Since you support PHP 5.6 I couldn't pull it from Composer, but the current approach should work

**Comment by dborsatto** [comment]
Yes, it builds 🎉 
Do you want to change something or can I merge? 🙂

**Comment by Jalle19** [comment]
@dborsatto feel free to merge

**Comment by dborsatto** [comment]
Thanks @Jalle19 🙂

**Pull request merged**
