### PR TITLE
Add ext-soap and phpunit/phpunit to require-dev

### PR DESCRIPTION
**Pull request by Jalle19**
Without this people will have to fiddle around in order to run the unit tests

### CODE REVIEW

**Comment by realityking** [comment]
Unfortunately I can't pull in phpunit as a dependency. It conflicts with some of the libraries I'm testing to generate classes for content types and keeping phpunit to a phar is an easy way to avoid the conflict.

What's the reason for the `ext-soap` dependency?

**Comment by Jalle19** [comment]
What libraries are those?

The `ext-soap` extension is a requirement for the test suite to run at all, without it you get this:

```
$ ./vendor/bin/phpunit 
PHP Fatal error:  Uncaught BadMethodCallException: For soap support you need to install the soap extension. in /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/SoapHook.php:47
Stack trace:
#0 /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/VCRFactory.php(60): VCR\LibraryHooks\SoapHook->__construct(Object(VCR\CodeTransform\SoapCodeTransform), Object(VCR\Util\StreamProcessor))
#1 [internal function]: VCR\VCRFactory->createVCRLibraryHooksSoapHook()
#2 /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/VCRFactory.php(119): call_user_func_array(Array, Array)
#3 /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/VCRFactory.php(98): VCR\VCRFactory->getOrCreate('VCR\\LibraryHook...', Array)
#4 /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php(288): VCR\VCRFactory::get('VCR\\LibraryHook...')
#5 /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/Videorecorder.php(122): VCR\Videorecorder->enableLibraryHooks in /home/negge/Projects/contentful.php/vendor/php-vcr/php-vcr/src/VCR/LibraryHooks/SoapHook.php on line 47
```

**Comment by Jalle19** [comment]
@realityking any update on this?

**Comment by dborsatto** [comment]
Hey Sam,
as regards to the `ext-soap` dependency, we shouldn't be the ones defining it, as it's actually PHP-VCR which relies on that (as you can also see in the stack trace you posted), so it's not really up to us to define a dependency's dependency 😉 
About the PHPUnit dependency, as Rouven said, for the moment there are some conflicts which are easily avoided using PHPUnit as `.phar`.

Because of these reasons, for the time being I'll close this, but I'll take a look in the future to see if we can improve the current situation 👍

**Comment by realityking** [comment]
I just opened #164, it hopefully takes care of the ext-soap issue.

**Comment by Jalle19** [comment]
> About the PHPUnit dependency, as Rouven said, for the moment there are some conflicts which are easily avoided using PHPUnit as .phar.

You have yet to explain what conflicts you're referring to here. As you can see from the Travis CI build output, adding `phpunit/phpunit` to `require-dev` works just fine.

**Pull request closed without merging**
