### PR TITLE
Implemented setters() and getters() for ResourceBuilder and InstanceCache

### PR DESCRIPTION
**Pull request by ArondeParon**
This allows for better extension of these objects, allowing developers to implement their own return types based on the Contentful API.

### CODE REVIEW

**Comment by Jalle19** [comment]
The `ResourceBuilder` is also needed to manually construct entry objects when parsing webhook payloads. Currently we have to make the object manually, which means we have to feed it a client and a cache instance etc., which is definitely not ideal.

**Comment by realityking** [comment]
@Jalle19 I admittedly have not tried it but wouldn't you be able to cover webhooks with `Client::reviveJson`? It would only work for the publish and unpublished events, other things might come in a format that's not understood by the SDK.

**Comment by Jalle19** [comment]
@realityking I'll check it out, hadn't seen that method before (possibly due to the slightly unobvious name)

**Comment by dborsatto** [comment]
Closing this because I'm planning to tackle the extensibility issue early 2018, but in a different way.

**Pull request closed without merging**
