### PR TITLE
Rerecords the test interactions due to some changes to the space we use.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by dborsatto** [comment]
Is this all of them?

**Comment by realityking** [comment]
Of course, I removed the entire directory and made completely new recordings.

**Comment by realityking** [comment]
I reverted the updates to 
* `tests/fixtures/e2e_sync_preview.json`
* and `tests/fixtures/e2e_sync_preview_continue.json`

Otherwise they'd record the API with the fix for #117. Since that fix is currently flagged to only some orgs I wanna keep the recording for the "broken" behaviour.

**Comment by dborsatto** [comment]
Ok 👍

**Pull request merged**
