### PR TITLE
Changed the behavior of getting an array of links to not throw an exception...

### PR DESCRIPTION
**Pull request by realityking**
... when one of them has been deleted from the space.

Closes #19.

### CODE REVIEW

**Comment by sgb-io** [comment]
👍

**Comment by graymic** [comment]
I can confirm this now fixes the issue we were facing, awesome stuff!

**Comment by realityking** [comment]
@graymic Great to hear. I just merged the commit into master.

Please note that the next release is a little bit off. We have a few backwards compatibility braking changes planned and I'd like to bundle as many as possible in the same release. You can always lock yourself to the git hash (6ab606d88c94d4431e09a5288725a89d13984de7) that has this fix until the next release comes out.

**Comment by graymic** [comment]
@realityking Perfect, will do.

**Pull request merged**
